apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: istio-backend1/istio-backend1
  name: istio-backend1
  namespace: istio-backend1
spec:
  limits:
  - type: Container
    max:
      cpu: '4'
      memory: 4G
